### ISSUE TITLE
[Feature] Display console.log or fails silently if default props are missing

### ISSUE THREAD

**Issue by foxted** [VariateApp/variate-react#2]
## Feature

When setting up Variate React in a project, not setting default props on a component will cause the app to crash.

## Ideal solution

I see two solutions here: 

- We can throw an exception in the console to remind the developer to set default props
- We can fail silently and use sensible defaults no matter what

**Comment by ghost** [comment]
I agree. I think we should use a sensible default instead of failing. That way if a user is using locals it's easier to implement

```js

const { content } = useVariate('Alert');

return (
 <div>
    <h1>{content.errort || t('alert.error')}</h1>
 </div>
)
```
